In [ ]:
import h5py
import pandas as pd
pd.options.mode.chained_assignment = None

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
data = h5py.File("/content/gdrive/My Drive/VDISC_train.hdf5",'r')
test = h5py.File("/content/gdrive/My Drive/VDISC_test.hdf5",'r')

In [ ]:
data.visit(print)

CWE-119
CWE-120
CWE-469
CWE-476
CWE-other
functionSource

In [ ]:
mydf = pd.DataFrame(list(data['functionSource']))
mydf['CWE-119']=list(data['CWE-119'])
mydf['CWE-120']=list(data['CWE-120'])
mydf['CWE-469']=list(data['CWE-469'])
mydf['CWE-476']=list(data['CWE-476'])
mydf['CWE-other']=list(data['CWE-other']) 


mydf.iloc[0:5,0:]

test_df = pd.DataFrame(list(test['functionSource']))
test_df['CWE-119'] = list(test['CWE-119'])
test_df['CWE-120'] = list(test['CWE-120'])
test_df['CWE-469'] = list(test['CWE-469'])
test_df['CWE-476' ]= list(test['CWE-476'])
test_df['CWE-other'] = list(test['CWE-other'])

test_df.iloc[0:5, 0:]

,0,CWE-119,CWE-120,CWE-469,CWE-476,CWE-other
0,"b'clear_area(int startx, int starty, int xsize...",False,False,False,False,False
1,b'ReconstructDuList(Statement* head)\n{\n S...,False,False,False,False,False
2,b'free_speaker(void)\n{\n if(Lengths)\n ...,False,False,False,False,False
3,b'mlx4_register_device(struct mlx4_dev *dev)\n...,False,False,False,False,False
4,"b'Parse_Env_Var(void)\n{\n char *p = getenv(""...",True,True,False,False,True

In [ ]:
mydf.rename(columns={0:'functionSource'},inplace=True)
mydf.iloc[0:5,0:]

test_df.rename(columns={0:'functionSource'}, inplace = True)
test_df.iloc[0:5, 0:]

,functionSource,CWE-119,CWE-120,CWE-469,CWE-476,CWE-other
0,b'default_event_handler( \n GuiWidget *widg...,False,False,False,False,False
1,"b'krb5_krbhst_init_flags(krb5_context context,...",False,False,False,False,False
2,b'swap_info_get(swp_entry_t entry)\n{\n\tstruc...,False,False,False,False,False
3,"b'parseattribs4(char *&c, const Vec4 &ival = V...",False,False,False,False,False
4,b'generateExecCode(CompileState* comp)\n{\n ...,False,False,False,False,False

In [ ]:
print(type(mydf["functionSource"][0]))
# for i in range(len(mydf)):
mydf["functionSource"] = mydf['functionSource'].str.decode("utf-8")

print(type(mydf["functionSource"][0]))
mydf.iloc[0:5,0:]

print(type(test_df["functionSource"][0]))
# for i in range(len(mydf)):
test_df["functionSource"] = test_df['functionSource'].str.decode("utf-8")

print(type(test_df["functionSource"][0]))
test_df.iloc[0:5,0:]

<class 'bytes'>
<class 'str'>
<class 'bytes'>
<class 'str'>

,functionSource,CWE-119,CWE-120,CWE-469,CWE-476,CWE-other
0,default_event_handler( \n GuiWidget *widget...,False,False,False,False,False
1,"krb5_krbhst_init_flags(krb5_context context,\n...",False,False,False,False,False
2,swap_info_get(swp_entry_t entry)\n{\n\tstruct ...,False,False,False,False,False
3,"parseattribs4(char *&c, const Vec4 &ival = Vec...",False,False,False,False,False
4,generateExecCode(CompileState* comp)\n{\n g...,False,False,False,False,False

Preprocessing some stuff

In [ ]:
code = mydf['functionSource']
code.head()

0    clear_area(int startx, int starty, int xsize, ...
1    ReconstructDuList(Statement* head)\n{\n    Sta...
2    free_speaker(void)\n{\n   if(Lengths)\n       ...
3    mlx4_register_device(struct mlx4_dev *dev)\n{\...
4    Parse_Env_Var(void)\n{\n  char *p = getenv("LI...
Name: functionSource, dtype: object

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
# import sklearn.metrics
# import pickle



# Generate random seed
myrand=np.random.randint(1, 99999 + 1)
# myrand=71926
np.random.seed(myrand)
tf.random.set_seed(myrand)
print("Random seed is:",myrand)

Random seed is: 92325

In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(char_level=False)
tokenizer.fit_on_texts(list(code))
# del(code)
print('Number of tokens: ',len(tokenizer.word_counts))
sorted(tokenizer.word_counts.items(), key=lambda x:x[1], reverse=True)[0:10]

Code cleaning,
i.e removing comments, whitespace, and also remapping all variables into the same

In [ ]:
def clean_code(code_part):
    # newregex = r"\b(?!alignas|class|alignof|not_eq|ifdef|co_yield|protected|noexcept|const_cast|namespace|error|consteval|thread_local|bool|throw|co_return|synchronized|module|explicit|mutable|and_eq|operator|co_await|for|catch|__has_include|pragma|or|continue|dynamic_cast|or_eq|signed|union|ifndef|xor_eq|void|else|goto|this|typedef|switch|virtual|char16_t|sizeof|concept|line|typename|requires|static_cast|try|false|private|default|char|while|break|asm|constinit|warning|true|unsigned|compl|transaction_safe_dynamic|define|override|friend|include|int|delete|atomic_cancel|using|reflexpr|bitand|xor|elifdef|enum|const|wchar_t|decltype|static|nullptr|not|reinterpret_cast|endif|atomic_commit|public|and|inline|long|static_assert|new|template|undef|char32_t|final|case|do|volatile|constexpr|register|atomic_noexcept|extern|bitor|export|float|char8_t|import|struct|defined|typeid|short|return|if|__has_cpp_attribute|double|transaction_safe|elif|elifndef|auto)\w+\b"
    import re
    regex_for_removing_single_line_comments = r"(//.*)|(/\*.*\*/)"
    code_part = code_part.replace(regex_for_removing_single_line_comments, "", regex=True)
    code_part = code_part.replace(r'\r+|\n+|\t+|  ','', regex=True)
    print(code_part[0])
    code_part.head()

    keywords = set(open("/content/gdrive/My Drive/keywords.csv", "r").read().split("\n"))

    regex_for_removing_variables = r"\b(?!" 
    regex_for_removing_variables += r"|".join(list(keywords))
    regex_for_removing_variables += r")\w+\b"

    print(regex_for_removing_variables)
    subst = "variable"

    # You can manually specify the number of replacements by changing the 4th argument
    code_part = code_part.replace(regex_for_removing_variables, subst, regex=True)
    
    print(type(code_part[0]), code_part[0])
    print(code_part.head())

    # Regex for removing comments

    regex_for_removing_multi_line_comments = r"(//.*)|(/\*.*\*/)"
    code_part = code_part.replace(regex_for_removing_multi_line_comments, "", regex=True)

    print(type(code_part[0]), code_part[0])
    print(code_part.head())
    return code_part

In [ ]:
code2 = clean_code(mydf["functionSource"])
print(len(code2), len(mydf))
mydf["functionSource"] = code2
init_count = 0
for i in mydf["functionSource"]:
    if "//" in i or "/*" in i:
        init_count += 1
# print(count)
curr_count = 0
for i in code2:
    if "//" in i or "/*" in i or "*/" in i:
        curr_count += 1
print(init_count, curr_count)
print("therefore cleaned {} comments".format(init_count - curr_count))



test_code = clean_code(test_df['functionSource'])
print(len(test_code), len(test_df))
test_df['functionSource'] = test_code
init_count = 0
for i in mydf["functionSource"]:
    if "//" in i or "/*" in i:
        init_count += 1
# print(count)
curr_count = 0
for i in test_code:
    if "//" in i or "/*" in i or "*/" in i:
        curr_count += 1
print(init_count, curr_count)
print("therefore cleaned {} comments".format(init_count - curr_count))
test_code

clear_area(int startx, int starty, int xsize, int ysize){int x;TRACE_LOG("Clearing area %d,%d / %d,%d\n", startx, starty, xsize, ysize);while (ysize > 0){x = xsize;while (x > 0){mvaddch(starty + ysize - 2, startx + x - 2, ' ');x--;}ysize--;}}
<class 'str'> clear_area(int startx, int starty, int xsize, int ysize){int x;TRACE_LOG("Clearing area %d,%d / %d,%d\n", startx, starty, xsize, ysize);while (ysize > 0){x = xsize;while (x > 0){mvaddch(starty + ysize - 2, startx + x - 2, ' ');x--;}ysize--;}}
0    clear_area(int startx, int starty, int xsize, ...
1    ReconstructDuList(Statement* head){Statement* ...
2    free_speaker(void){ if(Lengths) free(Lengths);...
3    mlx4_register_device(struct mlx4_dev *dev){str...
4    Parse_Env_Var(void){char *p = getenv("LINEDIT"...
Name: functionSource, dtype: object
1019471 1019471
390 456
therefore cleaned -66 comments
default_event_handler( GuiWidget *widget, GuiEvent *event ){char *ptr;int px, py, i;switch ( event->type ) {case GUI_DESTROY:if ( widget->spec.edit.buffer )free( widget->spec.edit.buffer );if ( widget->spec.edit.display_buffer )free( widget->spec.edit.display_buffer );break;case GUI_DRAW:stk_surface_blit( widget->surface, 0, 0, -1, -1, stk_display, widget->screen_region.x,widget->screen_region.y );gui_theme->edit_font->align = STK_FONT_ALIGN_LEFT;ptr = widget->spec.edit.display_buffer;px = widget->screen_region.x + widget->border;py = widget->screen_region.y + widget->border +  widget->spec.edit.y_offset;for ( i = 0; i < widget->spec.edit.height; i++, py += gui_theme->edit_font->height,ptr += widget->spec.edit.width + 1 )stk_font_write( gui_theme->edit_font,stk_display, px, py, -1, ptr );if ( widget == gui_key_widget || widget->focused )if ( gui_edit_blink )stk_surface_fill( stk_display, px + widget->spec.edit.x * gui_theme->edit_font->width,widget->screen_region.y + widget->border + widget->spec.edit.y_offset + widget->spec.edit.y * gui_theme->edit_font->height,1, gui_theme->edit_font->height,0xffffff );break;case GUI_KEY_PRESSED:if ( gui_edit_keysym != event->key.keysym ) {gui_edit_delay = 250;gui_edit_handle_key( widget, event->key.keysym,event->key.unicode );}break;case GUI_KEY_RELEASED:gui_edit_keysym = -1;break;case GUI_FOCUS_OUT:gui_edit_blink = 0;gui_widget_draw( widget );break;case GUI_CLICKED:stk_sound_play( gui_theme->click_sound );px = event->button.x - widget->screen_region.x - widget->border;py = event->button.y - widget->screen_region.y -widget->border - widget->spec.edit.y_offset;gui_edit_adjust_cursor( widget, (py / gui_theme->edit_font->height) * widget->spec.edit.width + (px / gui_theme->edit_font->width) + widget->spec.edit.start - widget->spec.edit.pos + 1 );gui_edit_blink = 1;gui_edit_blink_time = 0;gui_widget_draw( widget );break;}}
<class 'str'> default_event_handler( GuiWidget *widget, GuiEvent *event ){char *ptr;int px, py, i;switch ( event->type ) {case GUI_DESTROY:if ( widget->spec.edit.buffer )free( widget->spec.edit.buffer );if ( widget->spec.edit.display_buffer )free( widget->spec.edit.display_buffer );break;case GUI_DRAW:stk_surface_blit( widget->surface, 0, 0, -1, -1, stk_display, widget->screen_region.x,widget->screen_region.y );gui_theme->edit_font->align = STK_FONT_ALIGN_LEFT;ptr = widget->spec.edit.display_buffer;px = widget->screen_region.x + widget->border;py = widget->screen_region.y + widget->border +  widget->spec.edit.y_offset;for ( i = 0; i < widget->spec.edit.height; i++, py += gui_theme->edit_font->height,ptr += widget->spec.edit.width + 1 )stk_font_write( gui_theme->edit_font,stk_display, px, py, -1, ptr );if ( widget == gui_key_widget || widget->focused )if ( gui_edit_blink )stk_surface_fill( stk_display, px + widget->spec.edit.x * gui_theme->edit_font->width,widget->screen_region.y + widget->border + widget->spec.edit.y_offset + widget->spec.edit.y * gui_theme->edit_font->height,1, gui_theme->edit_font->height,0xffffff );break;case GUI_KEY_PRESSED:if ( gui_edit_keysym != event->key.keysym ) {gui_edit_delay = 250;gui_edit_handle_key( widget, event->key.keysym,event->key.unicode );}break;case GUI_KEY_RELEASED:gui_edit_keysym = -1;break;case GUI_FOCUS_OUT:gui_edit_blink = 0;gui_widget_draw( widget );break;case GUI_CLICKED:stk_sound_play( gui_theme->click_sound );px = event->button.x - widget->screen_region.x - widget->border;py = event->button.y - widget->screen_region.y -widget->border - widget->spec.edit.y_offset;gui_edit_adjust_cursor( widget, (py / gui_theme->edit_font->height) * widget->spec.edit.width + (px / gui_theme->edit_font->width) + widget->spec.edit.start - widget->spec.edit.pos + 1 );gui_edit_blink = 1;gui_edit_blink_time = 0;gui_widget_draw( widget );break;}}
0    default_event_handler( GuiWidget *widget, GuiE...
1    krb5_krbhst_init_flags(krb5_context context, c...
2    swap_info_get(swp_entry_t entry){struct swap_i...
3    parseattribs4(char *&c, const Vec4 &ival = Vec...
4    generateExecCode(CompileState* comp){generateD...
Name: functionSource, dtype: object
127419 127419
390 55
therefore cleaned 335 comments

0         default_event_handler( GuiWidget *widget, GuiE...
1         krb5_krbhst_init_flags(krb5_context context, c...
2         swap_info_get(swp_entry_t entry){struct swap_i...
3         parseattribs4(char *&c, const Vec4 &ival = Vec...
4         generateExecCode(CompileState* comp){generateD...
                                ...
127414    gucharmap_block_chapters_model_init (Gucharmap...
127415    scomp(const void *v1, const void *v2){struct P...
127416    text_chunk_line_free(TEXT_BUFFER_REC *buffer, ...
127417    psmouse_disconnect(struct serio *serio){struct...
127418    brasero_tool_dialog_get_burn (BraseroToolDialo...
Name: functionSource, Length: 127419, dtype: object

In [ ]:
mydf.head()

,functionSource,CWE-119,CWE-120,CWE-469,CWE-476,CWE-other
0,"clear_area(int startx, int starty, int xsize, ...",False,False,False,False,False
1,ReconstructDuList(Statement* head){Statement* ...,False,False,False,False,False
2,free_speaker(void){ if(Lengths) free(Lengths);...,False,False,False,False,False
3,mlx4_register_device(struct mlx4_dev *dev){str...,False,False,False,False,False
4,"Parse_Env_Var(void){char *p = getenv(""LINEDIT""...",True,True,False,False,True

### Cleaning flow ->

- Get code
- Replace all single line comments with the regex //*
- Replace all whitespaces -> \t \n \r and trailing spaces
- Replace all non keywords
- Replace all multi-line comments (now single line because of removing \n) with regex /* .* */

In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(char_level=False)
tokenizer.fit_on_texts(list(code2))
# del(code)
print('Number of tokens: ',len(tokenizer.word_counts))
sorted(tokenizer.word_counts.items(), key=lambda x:x[1], reverse=True)[0:10]

Number of tokens:  83573

[('variable', 56632241),
 ('if', 2650444),
 ('return', 1564071),
 ('int', 886956),
 ('struct', 600907),
 ('char', 539741),
 ('const', 528651),
 ('else', 431035),
 ('case', 392080),
 ('for', 384375)]

In [ ]:
init_count = 0
for i in mydf["functionSource"]:
    if "//" in i or "/*" in i:
        init_count += 1
# print(count)
curr_count = 0
for i in code2:
    if "//" in i or "/*" in i or "*/" in i:
        curr_count += 1
print(init_count, curr_count)
print("therefore cleaned {} comments".format(init_count - curr_count))

In [ ]:
print(type(code2), type(mydf))
print(len(code2), len(mydf))

mydf["functionSource"] = code2
print(mydf.head(n = 10))

<class 'pandas.core.series.Series'> <class 'pandas.core.frame.DataFrame'>
1019471 1019471
                                      functionSource  CWE-119  CWE-120  \
0  clear_area(int startx, int starty, int xsize, ...    False    False
1  ReconstructDuList(Statement* head){Statement* ...    False    False
2  free_speaker(void){ if(Lengths) free(Lengths);...    False    False
3  mlx4_register_device(struct mlx4_dev *dev){str...    False    False
4  Parse_Env_Var(void){char *p = getenv("LINEDIT"...     True     True
5  nilfs_superblock_sb_update_frequency_store(str...    False    False
6  r_HP_QP(jxr_image_t image, struct rbitstream*s...    False    False
7  PylonGuardJustDied(Creature* pCreature){for (u...    False    False
8  linda_ib_epb_wait ( struct linda *linda,struct...    False    False
9  median(const double *src, unsigned int len){un...    False    False

   CWE-469  CWE-476  CWE-other
0    False    False      False
1    False    False      False
2    False    False      False
3    False    False      False
4    False    False       True
5    False    False      False
6    False    False      False
7    False    False      False
8    False    False      False
9    False    False      False

# CNN implementation

In [ ]:
# mydf.to_pickle("VDISC_train.pickle")
# test_df.to_pickle("VDISC_test.pickle")
import pandas as pd
from google.colab import drive
drive.mount("/content/gdrive")
mydf=pd.read_pickle("/content/gdrive/My Drive/VDISC_train.pickle")
mydf = mydf.sample(frac=1).reset_index()
test_df=pd.read_pickle("/content/gdrive/My Drive/VDISC_test.pickle")

Mounted at /content/gdrive

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics
import pickle

print("Tensorlfow version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("GPU is", "available" if tf.test.is_gpu_available() else "NOT AVAILABLE")

WARNING:tensorflow:From <ipython-input-1-c66ca3651243>:10: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.

Tensorlfow version:  2.9.2
Eager mode:  True
GPU is available

In [ ]:


# Generate random seed
#myrand=np.random.randint(1, 99999 + 1)
myrand=71926
np.random.seed(myrand)
tf.random.set_seed(myrand)
print("Random seed is:",myrand)

Random seed is: 71926

In [ ]:
# Set the global value
WORDS_SIZE=10000
INPUT_SIZE=500
NUM_CLASSES=2
MODEL_NUM=0
EPOCHS=50

In [ ]:
mydf

,index,functionSource,CWE-119,CWE-120,CWE-469,CWE-476,CWE-other
0,438596,"variable(int variable, const char* variable, c...",0,0,0,0,0
1,218471,"variable(variable * variable, const variable &...",0,0,0,0,0
2,275275,"variable(variable::variable* variable,variable...",0,0,0,0,0
3,627691,"variable(const variable* variable, unsigned va...",0,0,0,0,0
4,640990,"variable (variable *variable, variable *variab...",0,0,0,0,0
...,...,...,...,...,...,...,...
1059804,530815,"variable(variable *variable, int variable, int...",0,0,0,0,0
1059805,338432,variable(variable * variable){variable *variab...,0,0,0,0,0
1059806,603632,"variable(variable variable, variable *variable...",0,0,0,0,0
1059807,163291,"variable(struct variable *variable,struct vari...",0,0,0,0,0
1059808,557760,variable(){variable variable;variable.variable...,0,0,0,0,0

In [ ]:
# ! No need for the loop if using dups dataset, else uncomment

# for dataset in [mydf, test_df]:
#     for col in range(1,6):
#         dataset.iloc[:,col] = dataset.iloc[:,col].map({False: 0, True: 1})

# Create source code sdata for tokenization
x_all = mydf['functionSource']
#x_all = x_all.append(validate['functionSource'])
#x_all = x_all.append(test['functionSource'])

In [ ]:
mydf

,index,functionSource,CWE-119,CWE-120,CWE-469,CWE-476,CWE-other
0,438596,"variable(int variable, const char* variable, c...",0,0,0,0,0
1,218471,"variable(variable * variable, const variable &...",0,0,0,0,0
2,275275,"variable(variable::variable* variable,variable...",0,0,0,0,0
3,627691,"variable(const variable* variable, unsigned va...",0,0,0,0,0
4,640990,"variable (variable *variable, variable *variab...",0,0,0,0,0
...,...,...,...,...,...,...,...
1059804,530815,"variable(variable *variable, int variable, int...",0,0,0,0,0
1059805,338432,variable(variable * variable){variable *variab...,0,0,0,0,0
1059806,603632,"variable(variable variable, variable *variable...",0,0,0,0,0
1059807,163291,"variable(struct variable *variable,struct vari...",0,0,0,0,0
1059808,557760,variable(){variable variable;variable.variable...,0,0,0,0,0

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=10000,lower=True)

tokenizer.fit_on_texts(mydf['functionSource'])
sequences = tokenizer.texts_to_sequences(mydf['functionSource'])
x = pad_sequences(sequences, maxlen=500)

pickle.dump(tokenizer, open("vuln_tokenizer.sav", 'wb'))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    x, 
    mydf[mydf.columns[2:]], 
    test_size=0.3, 
    shuffle=True
)

In [ ]:
y_train.columns

Index(['CWE-119', 'CWE-120', 'CWE-469', 'CWE-476', 'CWE-other'], dtype='object')

In [ ]:
num_classes = y_train.shape[1]
max_words = len(tokenizer.word_index) + 1
maxlen = 500

In [ ]:
from keras import backend as K
def avg_jacard(y_true,y_pred):
    '''
    see https://en.wikipedia.org/wiki/Multi-label_classification#Statistics_and_evaluation_metrics
    '''
    jacard = K.sum(K.minimum(y_true,y_pred)) / K.sum(K.maximum(y_true,y_pred))
    
    return K.mean(jacard)

In [ ]:
from keras.layers import Dense, Activation, Embedding, Flatten, GlobalMaxPool1D, Dropout, Conv1D
from keras.models import load_model
from keras.models import Sequential
from keras.layers import Dense, Embedding, GlobalMaxPool1D, Dropout
from tensorflow.keras.optimizers import Adam
from keras.callbacks import ReduceLROnPlateau, EarlyStopping, ModelCheckpoint
import tensorflow as tf

filter_length = 512

model = Sequential()
model.add(Embedding(max_words, 20, input_length=maxlen))
model.add(Conv1D(filter_length, 3, padding='valid', activation='relu'))
model.add(tf.keras.layers.MaxPool1D(pool_size=5))
model.add(tf.keras.layers.Dropout(0.2))
model.add(Conv1D(filter_length, 3, padding='valid', activation='relu'))
model.add(tf.keras.layers.MaxPool1D(pool_size=5))
model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(Dense(num_classes))
model.add(Activation('sigmoid'))

model.compile(
    optimizer='adam', 
    loss='binary_crossentropy', 
    metrics=[
        tf.keras.metrics.AUC(),
        tf.keras.metrics.Accuracy()
        tf.keras.metrics.Precision(),
        tf.keras.metrics.Recall()
    ]
)

callbacks = [
    ReduceLROnPlateau(),
    ModelCheckpoint(filepath='model-conv1d.h5', save_best_only=True)
]

history = model.fit(X_train, y_train,
                    epochs=30,
                    batch_size=32,
                    validation_split=0.2,
                    callbacks=callbacks)

Epoch 1/30
6032/6032 [==============================] - 101s 17ms/step - loss: 0.2670 - auc_1: 0.8091 - accuracy: 0.0000e+00 - precision_1: 0.5420 - recall_1: 0.0755 - val_loss: 0.2508 - val_auc_1: 0.8397 - val_accuracy: 0.0000e+00 - val_precision_1: 0.5668 - val_recall_1: 0.1683 - lr: 0.0010
Epoch 2/30
6032/6032 [==============================] - 101s 17ms/step - loss: 0.2431 - auc_1: 0.8485 - accuracy: 2.0726e-06 - precision_1: 0.6484 - recall_1: 0.1965 - val_loss: 0.2355 - val_auc_1: 0.8604 - val_accuracy: 0.0000e+00 - val_precision_1: 0.6700 - val_recall_1: 0.2597 - lr: 0.0010
Epoch 3/30
6032/6032 [==============================] - 98s 16ms/step - loss: 0.2280 - auc_1: 0.8678 - accuracy: 4.2488e-05 - precision_1: 0.6974 - recall_1: 0.2791 - val_loss: 0.2245 - val_auc_1: 0.8723 - val_accuracy: 3.7306e-05 - val_precision_1: 0.7172 - val_recall_1: 0.2939 - lr: 0.0010
Epoch 4/30
6032/6032 [==============================] - 101s 17ms/step - loss: 0.2174 - auc_1: 0.8805 - accuracy: 2.1762e-04 - precision_1: 0.7222 - recall_1: 0.3259 - val_loss: 0.2179 - val_auc_1: 0.8793 - val_accuracy: 1.9068e-04 - val_precision_1: 0.6999 - val_recall_1: 0.3670 - lr: 0.0010
Epoch 5/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.2080 - auc_1: 0.8905 - accuracy: 5.5131e-04 - precision_1: 0.7470 - recall_1: 0.3649 - val_loss: 0.2102 - val_auc_1: 0.8876 - val_accuracy: 3.4819e-04 - val_precision_1: 0.7747 - val_recall_1: 0.3528 - lr: 0.0010
Epoch 6/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.2000 - auc_1: 0.8987 - accuracy: 9.0573e-04 - precision_1: 0.7656 - recall_1: 0.3942 - val_loss: 0.2085 - val_auc_1: 0.8904 - val_accuracy: 8.8707e-04 - val_precision_1: 0.7431 - val_recall_1: 0.4128 - lr: 0.0010
Epoch 7/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1940 - auc_1: 0.9046 - accuracy: 0.0012 - precision_1: 0.7800 - recall_1: 0.4149 - val_loss: 0.2024 - val_auc_1: 0.8957 - val_accuracy: 7.9587e-04 - val_precision_1: 0.8028 - val_recall_1: 0.3930 - lr: 0.0010
Epoch 8/30
6032/6032 [==============================] - 97s 16ms/step - loss: 0.1883 - auc_1: 0.9099 - accuracy: 0.0017 - precision_1: 0.7957 - recall_1: 0.4332 - val_loss: 0.1996 - val_auc_1: 0.8982 - val_accuracy: 0.0012 - val_precision_1: 0.7772 - val_recall_1: 0.4232 - lr: 0.0010
Epoch 9/30
6032/6032 [==============================] - 97s 16ms/step - loss: 0.1828 - auc_1: 0.9150 - accuracy: 0.0023 - precision_1: 0.8080 - recall_1: 0.4509 - val_loss: 0.2020 - val_auc_1: 0.8966 - val_accuracy: 0.0018 - val_precision_1: 0.8469 - val_recall_1: 0.3894 - lr: 0.0010
Epoch 10/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1785 - auc_1: 0.9189 - accuracy: 0.0031 - precision_1: 0.8142 - recall_1: 0.4654 - val_loss: 0.1973 - val_auc_1: 0.9008 - val_accuracy: 0.0022 - val_precision_1: 0.8330 - val_recall_1: 0.4152 - lr: 0.0010
Epoch 11/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1745 - auc_1: 0.9222 - accuracy: 0.0034 - precision_1: 0.8223 - recall_1: 0.4784 - val_loss: 0.1984 - val_auc_1: 0.9010 - val_accuracy: 0.0027 - val_precision_1: 0.8427 - val_recall_1: 0.4205 - lr: 0.0010
Epoch 12/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1711 - auc_1: 0.9249 - accuracy: 0.0040 - precision_1: 0.8289 - recall_1: 0.4919 - val_loss: 0.1989 - val_auc_1: 0.9011 - val_accuracy: 0.0022 - val_precision_1: 0.8417 - val_recall_1: 0.4262 - lr: 0.0010
Epoch 13/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1680 - auc_1: 0.9275 - accuracy: 0.0042 - precision_1: 0.8324 - recall_1: 0.5023 - val_loss: 0.1979 - val_auc_1: 0.9035 - val_accuracy: 0.0038 - val_precision_1: 0.8059 - val_recall_1: 0.4637 - lr: 0.0010
Epoch 14/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1652 - auc_1: 0.9299 - accuracy: 0.0050 - precision_1: 0.8354 - recall_1: 0.5107 - val_loss: 0.1956 - val_auc_1: 0.9059 - val_accuracy: 0.0040 - val_precision_1: 0.7805 - val_recall_1: 0.4847 - lr: 0.0010
Epoch 15/30
6032/6032 [==============================] - 98s 16ms/step - loss: 0.1626 - auc_1: 0.9321 - accuracy: 0.0055 - precision_1: 0.8425 - recall_1: 0.5215 - val_loss: 0.1951 - val_auc_1: 0.9056 - val_accuracy: 0.0043 - val_precision_1: 0.7974 - val_recall_1: 0.4821 - lr: 0.0010
Epoch 16/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1602 - auc_1: 0.9338 - accuracy: 0.0056 - precision_1: 0.8455 - recall_1: 0.5296 - val_loss: 0.1909 - val_auc_1: 0.9093 - val_accuracy: 0.0051 - val_precision_1: 0.8079 - val_recall_1: 0.4785 - lr: 0.0010
Epoch 17/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1581 - auc_1: 0.9355 - accuracy: 0.0062 - precision_1: 0.8463 - recall_1: 0.5377 - val_loss: 0.1949 - val_auc_1: 0.9071 - val_accuracy: 0.0057 - val_precision_1: 0.7726 - val_recall_1: 0.5095 - lr: 0.0010
Epoch 18/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1558 - auc_1: 0.9374 - accuracy: 0.0067 - precision_1: 0.8502 - recall_1: 0.5459 - val_loss: 0.1947 - val_auc_1: 0.9087 - val_accuracy: 0.0054 - val_precision_1: 0.7907 - val_recall_1: 0.4990 - lr: 0.0010
Epoch 19/30
6032/6032 [==============================] - 97s 16ms/step - loss: 0.1534 - auc_1: 0.9392 - accuracy: 0.0072 - precision_1: 0.8533 - recall_1: 0.5535 - val_loss: 0.1959 - val_auc_1: 0.9088 - val_accuracy: 0.0051 - val_precision_1: 0.8025 - val_recall_1: 0.4946 - lr: 0.0010
Epoch 20/30
6032/6032 [==============================] - 95s 16ms/step - loss: 0.1517 - auc_1: 0.9405 - accuracy: 0.0075 - precision_1: 0.8560 - recall_1: 0.5613 - val_loss: 0.2020 - val_auc_1: 0.9065 - val_accuracy: 0.0067 - val_precision_1: 0.8193 - val_recall_1: 0.4899 - lr: 0.0010
Epoch 21/30
6032/6032 [==============================] - 95s 16ms/step - loss: 0.1498 - auc_1: 0.9421 - accuracy: 0.0075 - precision_1: 0.8580 - recall_1: 0.5682 - val_loss: 0.1996 - val_auc_1: 0.9088 - val_accuracy: 0.0064 - val_precision_1: 0.8035 - val_recall_1: 0.5029 - lr: 0.0010
Epoch 22/30
6032/6032 [==============================] - 97s 16ms/step - loss: 0.1478 - auc_1: 0.9435 - accuracy: 0.0080 - precision_1: 0.8599 - recall_1: 0.5725 - val_loss: 0.1987 - val_auc_1: 0.9090 - val_accuracy: 0.0079 - val_precision_1: 0.7988 - val_recall_1: 0.5020 - lr: 0.0010
Epoch 23/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1466 - auc_1: 0.9443 - accuracy: 0.0079 - precision_1: 0.8623 - recall_1: 0.5771 - val_loss: 0.2008 - val_auc_1: 0.9076 - val_accuracy: 0.0070 - val_precision_1: 0.8419 - val_recall_1: 0.4865 - lr: 0.0010
Epoch 24/30
6032/6032 [==============================] - 95s 16ms/step - loss: 0.1455 - auc_1: 0.9452 - accuracy: 0.0076 - precision_1: 0.8620 - recall_1: 0.5824 - val_loss: 0.2006 - val_auc_1: 0.9069 - val_accuracy: 0.0077 - val_precision_1: 0.8319 - val_recall_1: 0.4933 - lr: 0.0010
Epoch 25/30
6032/6032 [==============================] - 96s 16ms/step - loss: 0.1438 - auc_1: 0.9465 - accuracy: 0.0085 - precision_1: 0.8665 - recall_1: 0.5871 - val_loss: 0.1980 - val_auc_1: 0.9106 - val_accuracy: 0.0086 - val_precision_1: 0.8165 - val_recall_1: 0.5029 - lr: 0.0010
Epoch 26/30
6032/6032 [==============================] - 97s 16ms/step - loss: 0.1424 - auc_1: 0.9473 - accuracy: 0.0087 - precision_1: 0.8688 - recall_1: 0.5912 - val_loss: 0.2095 - val_auc_1: 0.9087 - val_accuracy: 0.0095 - val_precision_1: 0.7648 - val_recall_1: 0.5409 - lr: 0.0010
Epoch 27/30
6032/6032 [==============================] - 94s 16ms/step - loss: 0.1330 - auc_1: 0.9543 - accuracy: 0.0104 - precision_1: 0.8802 - recall_1: 0.6181 - val_loss: 0.2058 - val_auc_1: 0.9104 - val_accuracy: 0.0106 - val_precision_1: 0.7979 - val_recall_1: 0.5317 - lr: 1.0000e-04
Epoch 28/30
6032/6032 [==============================] - 94s 16ms/step - loss: 0.1301 - auc_1: 0.9557 - accuracy: 0.0113 - precision_1: 0.8847 - recall_1: 0.6268 - val_loss: 0.2070 - val_auc_1: 0.9104 - val_accuracy: 0.0112 - val_precision_1: 0.7982 - val_recall_1: 0.5336 - lr: 1.0000e-04
Epoch 29/30
6032/6032 [==============================] - 95s 16ms/step - loss: 0.1284 - auc_1: 0.9567 - accuracy: 0.0121 - precision_1: 0.8872 - recall_1: 0.6323 - val_loss: 0.2087 - val_auc_1: 0.9104 - val_accuracy: 0.0118 - val_precision_1: 0.7975 - val_recall_1: 0.5365 - lr: 1.0000e-04
Epoch 30/30
6032/6032 [==============================] - 94s 16ms/step - loss: 0.1272 - auc_1: 0.9575 - accuracy: 0.0126 - precision_1: 0.8874 - recall_1: 0.6348 - val_loss: 0.2116 - val_auc_1: 0.9100 - val_accuracy: 0.0126 - val_precision_1: 0.7878 - val_recall_1: 0.5459 - lr: 1.0000e-04

In [ ]:
save_option = tf.saved_model.SaveOptions(experimental_io_device="/job:localhost")
model.save("/content/gdrive/My Drive/vuln_model", options=save_option)

WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 2 of 2). These functions will not be directly callable after loading.

In [ ]:

cnn_model = tf.keras.models.load_model('/content/gdrive/My Drive/vuln_model')
metrics = cnn_model.evaluate(X_test, y_test)
print("{}: {}".format(cnn_model.metrics_names[1], metrics[1]))
print("{}: {}".format(cnn_model.metrics_names[2], metrics[2]))
print("{}: {}".format(cnn_model.metrics_names[3], metrics[3]))
print("{}: {}".format(cnn_model.metrics_names[4], metrics[4]))
#print("{}: {}".format(cnn_model.metrics_names[5], metrics[5]))

3231/3231 [==============================] - 24s 7ms/step - loss: 0.2137 - auc_1: 0.9102 - accuracy: 0.0127 - precision_1: 0.7844 - recall_1: 0.5440
auc_1: 0.9101868271827698
accuracy: 0.012662732973694801
precision_1: 0.7843882441520691
recall_1: 0.5439600944519043

In [ ]:
y_pred = cnn_model.predict(X_test)

2784/2784 [==============================] - 12s 4ms/step

In [ ]:
def transform(pred,threshold):
  for i in range(len(pred)):
    for j in range(len(pred[0])):
      if pred[i][j] < threshold:
        pred[i][j] = 0
      else:
        pred[i][j] = 1
  return pred

In [ ]:
y_pred = transform(y_pred,0.4)

In [ ]:
y_true = []
for i in range(len(y_test)):
  y_true.append([])
  for num in y_test.iloc[i]:
    y_true[-1].append(num)
y_true = np.array(y_true)
y_true.shape
#y_test.iloc[0][2]

(89087, 5)

In [ ]:
from sklearn.metrics import classification_report
label_names = ["119","120",'469','476','other']

print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

         119       0.63      0.67      0.65      8584
         120       0.61      0.64      0.63     15699
         469       0.93      0.98      0.95      6926
         476       0.76      0.57      0.65      9409
       other       0.60      0.48      0.53     12120

   micro avg       0.68      0.64      0.66     52738
   macro avg       0.71      0.67      0.68     52738
weighted avg       0.68      0.64      0.66     52738
 samples avg       0.20      0.20      0.19     52738

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
result = pd.DataFrame({"Code" : [],"Expected Vuln" : [], "Predicted Vuln" : []})

In [ ]:
# sample = test_df[(test_df["CWE-119"] == 1) | (test_df["CWE-120"] == 1) | (test_df["CWE-469"] == 1) | (test_df["CWE-476"] == 1) | (test_df["CWE-other"] == 1)].sample(10)
# sample.append(test_df)
sample = test_df.sample(10)
for i in range(len(sample)):
  current = pd.DataFrame({"Question" : [sample.iloc[i]["functionSource"]],"Expected Tags" : [[sample.iloc[i]["CWE-119"],sample.iloc[i]["CWE-120"],sample.iloc[i]["CWE-469"],sample.iloc[i]["CWE-476"],sample.iloc[i]["CWE-other"]]], "Predicted Tags" : [getTags(sample.iloc[i]["functionSource"],0.3)]})
  #print(current)
  result = result.append(current)

1/1 [==============================] - 0s 27ms/step
1/1 [==============================] - 0s 28ms/step
1/1 [==============================] - 0s 27ms/step
1/1 [==============================] - 0s 27ms/step
1/1 [==============================] - 0s 28ms/step
1/1 [==============================] - 0s 25ms/step
1/1 [==============================] - 0s 24ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 23ms/step
1/1 [==============================] - 0s 15ms/step

In [ ]:
result

,Question,Expected Tags,Predicted Tags
0,"variable(struct variable *variable, int variab...","[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"
0,"variable(unsigned int variable, unsigned int v...","[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"
0,"variable(struct variable *variable, const vari...","[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"
0,variable(const char *variable){variable *varia...,"[False, False, True, True, False]","[[0.0, 0.0, 0.0, 0.0, 1.0]]"
0,variable(variable& variable){for (unsigned int...,"[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"
0,"variable(variable, variable, variable, variabl...","[False, False, False, False, False]","[[0.0, 1.0, 0.0, 0.0, 0.0]]"
0,variable(variable *variable){int variable = va...,"[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"
0,"variable(struct variable *variable, int variab...","[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"
0,variable(variable variable){if (variable & var...,"[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"
0,"variable(struct variable*variable,struct varia...","[False, False, False, False, False]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"